# Generated by Django 5.2 on 2025-05-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
    ]
