# Generated by Django 5.2 on 2025-05-14 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_category_location_alter_plant_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.location', to_field='name'),
        ),
    ]
